import {
    HiOutlineDocumentText,
    HiOutlineShieldCheck,
    HiOutlineUser,
    HiOutlineLockClosed,
    HiOutlineArrowPath,
    HiOutlineExclamationCircle,
} from "react-icons/hi2";
import { MdGavel, MdContactMail } from "react-icons/md";

export default function TermsConditions() {
    return (
        <div className="mt-[15vh]">
            <div className="px-5 md:px-12 lg:px-16 xl:px-0 max-w-7xl mx-auto">

                {/* Header */}
                <div className="flex items-center gap-4 mb-10">
                    <div className="p-3 rounded-xl bg-gray-100">
                        <HiOutlineShieldCheck className="text-3xl text-gray-800" />
                    </div>
                    <h1 className="text-3xl md:text-4xl font-bold tracking-tight">
                        Terms & Conditions
                    </h1>
                </div>

                {/* Legal Basis & Electronic Record */}
                <section className="section_topSpace space-y-4">
                    <div className="flex items-center gap-3">
                        <span className="p-2 rounded-lg bg-gray-100">
                            <HiOutlineDocumentText className="text-xl" />
                        </span>
                        <h2 className="text-xl font-semibold">Legal Basis & Electronic Record</h2>
                    </div>
                    <p>
                        This document is an electronic record in terms of the Information Technology Act, 2000 and its rules, including amendments pertaining to electronic records.
                        It is generated by a computer system and does not require any physical or digital signatures.
                    </p>
                    <p>
                        This document is published in accordance with Rule 3(1) of the Information Technology (Intermediaries Guidelines) Rules, 2011, which requires publishing rules, regulations,
                        privacy policy, and Terms of Use for access or usage of the domain <strong>stockcircle.in</strong> ('Website'), including the mobile site and mobile application ('Platform').
                    </p>
                    <p>
                        The Platform is owned by <strong>StockCircle</strong>, a company incorporated under the Companies Act, 1956, with registered office at S28, B Wing, Express Zone Mall, Goregaon East, Mumbai
                        (hereinafter ‘Platform Owner’, 'we', 'us', 'our').
                    </p>
                </section>

                {/* Applicability */}
                <section className="section_topSpace space-y-4">
                    <div className="flex items-center gap-3">
                        <span className="p-2 rounded-lg bg-gray-100">
                            <MdGavel className="text-xl" />
                        </span>
                        <h2 className="text-xl font-semibold">Applicability & Binding Terms</h2>
                    </div>
                    <p>
                        Your use of the Platform, services, and tools is governed by these Terms of Use and applicable policies, incorporated herein by reference.
                        By using the Platform, you enter into a binding contract with the Platform Owner. Any conflicting terms proposed by you are expressly rejected.
                    </p>
                    <p>
                        These Terms may be modified at any time without notice. It is your responsibility to periodically review these Terms to stay informed of updates.
                    </p>
                    <p>
                        'You', 'your', or 'user' refers to any natural or legal person who agrees to become a user/buyer on the Platform.
                    </p>
                </section>

                {/* Agreement to Terms */}
                <section className="section_topSpace space-y-4">
                    <div className="flex items-center gap-3">
                        <span className="p-2 rounded-lg bg-gray-100">
                            <HiOutlineUser className="text-xl" />
                        </span>
                        <h2 className="text-xl font-semibold">Agreement to Terms</h2>
                    </div>
                    <p>
                        ACCESSING, BROWSING, OR USING THE PLATFORM INDICATES YOUR AGREEMENT TO ALL TERMS AND CONDITIONS UNDER THESE TERMS OF USE. PLEASE READ CAREFULLY.
                    </p>
                    <p>
                        To access and use the Services, you agree to provide true, accurate, and complete information during registration. You are responsible for all acts performed through your registered account.
                    </p>
                </section>

                {/* Warranties & Liability */}
                <section className="section_topSpace space-y-4">
                    <div className="flex items-center gap-3">
                        <span className="p-2 rounded-lg bg-gray-100">
                            <HiOutlineExclamationCircle className="text-xl" />
                        </span>
                        <h2 className="text-xl font-semibold">Warranties & Liability</h2>
                    </div>
                    <p>
                        Neither we nor any third parties provide warranties regarding the accuracy, timeliness, performance, completeness, or suitability of the information or materials on this Platform or Services.
                    </p>
                    <p>
                        Your use of the Platform and Services is entirely at your own risk. You are responsible for independently assessing whether the Services meet your requirements.
                    </p>
                    <p>
                        All contents of the Platform and Services are proprietary and licensed to us. You shall not claim any intellectual property rights over the content, design, layout, look, or graphics.
                    </p>
                    <p>
                        Unauthorized use of the Platform or Services may lead to legal action as per these Terms and applicable laws.
                    </p>
                </section>

                {/* Payments & Use Restrictions */}
                <section className="section_topSpace space-y-4">
                    <div className="flex items-center gap-3">
                        <span className="p-2 rounded-lg bg-gray-100">
                            <HiOutlineLockClosed className="text-xl" />
                        </span>
                        <h2 className="text-xl font-semibold">Payments & Use Restrictions</h2>
                    </div>
                    <p>
                        You agree to pay charges associated with availing Services. You agree not to use the Platform or Services for unlawful purposes or in violation of applicable laws.
                    </p>
                    <p>
                        The Platform may contain links to third-party websites. Accessing these links is governed by the third party’s terms, privacy policies, and rules. These links are for convenience only.
                    </p>
                    <p>
                        Initiating a transaction for Services establishes a legally binding contract with the Platform Owner.
                    </p>
                </section>

                {/* Indemnity */}
                <section className="section_topSpace space-y-4">
                    <div className="flex items-center gap-3">
                        <span className="p-2 rounded-lg bg-gray-100">
                            <MdGavel className="text-xl" />
                        </span>
                        <h2 className="text-xl font-semibold">Indemnity</h2>
                    </div>
                    <p>
                        You shall indemnify and hold harmless the Platform Owner, affiliates, group companies, and their officers, directors, agents, and employees from any claim, demand, or action, including reasonable attorney fees, arising from your breach of these Terms, Privacy Policy, or applicable laws.
                    </p>
                </section>

                {/* Force Majeure */}
                <section className="section_topSpace space-y-4">
                    <div className="flex items-center gap-3">
                        <span className="p-2 rounded-lg bg-gray-100">
                            <HiOutlineArrowPath className="text-xl" />
                        </span>
                        <h2 className="text-xl font-semibold">Force Majeure</h2>
                    </div>
                    <p>
                        Neither party shall be liable for failure to perform obligations under these Terms if performance is prevented or delayed by a force majeure event.
                    </p>
                </section>

                {/* Governing Law & Jurisdiction */}
                <section className="section_topSpace space-y-4">
                    <div className="flex items-center gap-3">
                        <span className="p-2 rounded-lg bg-gray-100">
                            <MdGavel className="text-xl" />
                        </span>
                        <h2 className="text-xl font-semibold">Governing Law & Jurisdiction</h2>
                    </div>
                    <p>
                        These Terms and any disputes relating to them shall be governed by and construed in accordance with the laws of India. All disputes are subject to the exclusive jurisdiction of courts in India.
                    </p>
                </section>

                {/* Contact Information */}
                <section className="section_topSpace space-y-4 border-t pt-8">
                    <div className="flex items-center gap-3">
                        <span className="p-2 rounded-lg bg-gray-100">
                            <MdContactMail className="text-xl" />
                        </span>
                        <h2 className="text-xl font-semibold">Contact Information</h2>
                    </div>
                    <p>
                        All concerns or communications relating to these Terms must be sent using the contact information provided on this website.
                    </p>
                </section>

            </div>
        </div>
    );
}
