import { Poppins } from 'next/font/google'
import './globals.css'
import Footer from './(client)/_components/Shared/Footer/Footer'


const poppins = Poppins({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin']
})



export const metadata = {
  title: 'Stock Circle',
  description: 'Generated by create next app'
}
// footer__gradient__color
export default function RootLayout ({ children }) {
  return (
    <html lang='en' data-arp=''>
      <body
        cz-shortcut-listen='true'
        className={`${poppins.className}  bg-gray-50  antialiased`}
      >
        {/* <Header /> */}
        {children}
      </body>
    </html>
  )
}

